[2025-02-16T15:29:21.318+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-16T15:29:21.340+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline_dag.export_to_db manual__2025-02-16T15:29:14.914477+00:00 [queued]>
[2025-02-16T15:29:21.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline_dag.export_to_db manual__2025-02-16T15:29:14.914477+00:00 [queued]>
[2025-02-16T15:29:21.349+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-02-16T15:29:21.362+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): export_to_db> on 2025-02-16 15:29:14.914477+00:00
[2025-02-16T15:29:21.367+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1172) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-16T15:29:21.369+0000] {standard_task_runner.py:63} INFO - Started process 1174 to run task
[2025-02-16T15:29:21.369+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline_dag', 'export_to_db', 'manual__2025-02-16T15:29:14.914477+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpxdrljue1']
[2025-02-16T15:29:21.372+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask export_to_db
[2025-02-16T15:29:21.413+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline_dag.export_to_db manual__2025-02-16T15:29:14.914477+00:00 [running]> on host dfa5576bf540
[2025-02-16T15:29:21.495+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='export_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T15:29:14.914477+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T15:29:14.914477+00:00'
[2025-02-16T15:29:21.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-16T15:29:21.527+0000] {base.py:84} INFO - Using connection ID 'postgres_weather' for task execution.
[2025-02-16T15:29:21.533+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-16T15:29:21.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-16T15:29:21.542+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline_dag, task_id=export_to_db, run_id=manual__2025-02-16T15:29:14.914477+00:00, execution_date=20250216T152914, start_date=20250216T152921, end_date=20250216T152921
[2025-02-16T15:29:21.584+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-16T15:29:21.605+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T15:29:21.608+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
